

const SESSION_STORAGE_DEVTOOLS_PANEL_ACTIVATED_KEY = 'Solid::Devtools::devtoolsPanelActivated';
const SESSION_STORAGE_DEVTOOLS_EXPOSE_NODE_IDS_KEY = 'Solid::Devtools::exposeNodeIds';
const SESSION_STORAGE_DEVTOOLS_EXPOSE_DEBUGGER_HACK = 'Solid::Devtools::exposeDebuggerHack';
const LOCAL_STORAGE_DEVTOOLS_COMPONENTS_PANEL_RESIZE_KEY = 'Solid::Devtools::componentsPanelResize';

export {SESSION_STORAGE_DEVTOOLS_PANEL_ACTIVATED_KEY, SESSION_STORAGE_DEVTOOLS_EXPOSE_NODE_IDS_KEY, SESSION_STORAGE_DEVTOOLS_EXPOSE_DEBUGGER_HACK, LOCAL_STORAGE_DEVTOOLS_COMPONENTS_PANEL_RESIZE_KEY};
