

const SESSION_STORAGE_DEVTOOLS_PANEL_ACTIVATED_KEY = 'Solid::Devtools::devtoolsPanelActivated';
const SESSION_STORAGE_DEVTOOLS_EXPOSE_NODE_IDS_KEY = 'Solid::Devtools::exposeNodeIds';
const LOCAL_STORAGE_DEVTOOLS_COMPONENTS_PANEL_RESIZE_KEY = 'Solid::Devtools::componentsPanelResize';

export {SESSION_STORAGE_DEVTOOLS_PANEL_ACTIVATED_KEY, SESSION_STORAGE_DEVTOOLS_EXPOSE_NODE_IDS_KEY, LOCAL_STORAGE_DEVTOOLS_COMPONENTS_PANEL_RESIZE_KEY};
