

const SESSION_STORAGE_DEVTOOLS_PANEL_ACTIVATED_KEY = 'Solid::Devtools::devtoolsPanelActivated';
const SESSION_STORAGE_DEVTOOLS_EXPOSE_NODE_IDS_KEY = 'Solid::Devtools::exposeNodeIds';

export {SESSION_STORAGE_DEVTOOLS_PANEL_ACTIVATED_KEY, SESSION_STORAGE_DEVTOOLS_EXPOSE_NODE_IDS_KEY};
